_default_:
  code: "_default_"
  desc: "默认"
  item:
    name:
      code: "name"
      desc: "名称"
      process:
        - kind: fmtfn
          op: "trim"
          val: ""
        - kind: check
          op: "range"
          val: "2,20"
    age:
      code: "age"
      desc: "用户年龄"
      process:
        - kind: check
          op: "lt"
          val: "200"
user:
  code: "user"
  desc: "用户"
  item:
    name:
      code: "name"
      desc: "用户名称"
      process:
        - kind: fmtfn
          op: "trim"
          val: ""
        - kind: check
          op: "range"
          val: "2,20"
    desc:
      code: "desc"
      desc: "用户描述"
      process:
        - kind: fmtfn
          op: "trim"
          val: ""
        - kind: check
          op: "lt"
          val: "200"